# https://hub.docker.com/r/openliberty/open-liberty
FROM FROM open-liberty:beta-java11

ADD --chown=1001:0 target/dependency/postgresql-42.2.19.jar /opt/ol/wlp/usr/shared/resources/postgresql/postgresql.jar