# https://hub.docker.com/r/openliberty/open-liberty
FROM open-liberty:22.0.0.4-full-java17-openj9

ADD --chown=1001:0 target/dependency/postgresql-42.3.5.jar /opt/ol/wlp/usr/shared/resources/postgresql/postgresql.jar