version: '3.7'

services:
  postgresql:
    build: ./docker/postgresql
    networks:
      - torganizer
    ports:
      - 5432:5432
    container_name: postgresql
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_user_password
  frontend:
    build: ./frontend
    networks:
      - torganizer
    ports:
      - 8080:8080
    container_name: frontend
    env_file:
      - ./frontend/src/main/liberty/config/server.env
    
networks:
  torganizer:
    driver: bridge