version: '3.7'

services:
  database:
    build: ./docker/mysql
    ports:
      - 3306:3306
  rest:
    build: ./rest
    ports:
      - 9080:9080
    environment:
      mysql.server.port: 3306
      mysql.server.name: 0.0.0.0
      mysql.user: root
      mysql.password: root