version: '3.7'

services:
  prometheus:
    build: ./docker/prometheus
    networks:
      - torganizer
    ports:
      - 9090:9090
    container_name: prometheus
  grafana:
    build: ./docker/grafana
    networks:
      - torganizer
    ports:
      - 3000:3000
    container_name: grafana
  postgresql:
    build: ./docker/postgresql
    networks:
      - torganizer
    ports:
      - 5432:5432
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  frontend:
    build: ./frontend
    networks:
      - torganizer
    ports:
      - 8080:8080
    container_name: frontend
    environment:
      dataSource_serverName: postgresql
      dataSource_portNumber: 5432
      dataSource_user: postgres
      dataSource_password: postgres

networks:
  torganizer:
    driver: bridge