version: '3.7'

services:
  postgresql:
    build: ./docker/postgresql
    networks:
      - torganizer
    ports:
      - 5432:5432
    container_name: postgresql
  rest:
    build: ./rest
    networks:
      - torganizer
    depends_on:
      - "postgresql"
    ports:
      - 9080:9080
    container_name: rest
    environment:
      dataSource_portNumber: 5432
      dataSource_serverName: postgresql
      dataSource_user: postgres
      dataSource_password: postgres
  webclient:
    build: ./webclient
    networks:
      - torganizer
    ports:
      - 8080:8080
    container_name: webclient
    environment:
      resources_url: http://localhost:9080/rest/resources/      
networks:
  torganizer:
    driver: bridge