version: '3.7'

services:
  postgresql:
    build: ./docker/postgresql
    networks:
      - torganizer
    ports:
      - 5432:5432
    container_name: postgresql
  rest:
    build: ./rest
    networks:
      - torganizer
    depends_on:
      - "postgresql"
    ports:
      - 9080:9080
    container_name: rest
  webclient:
    build: ./webclient
    networks:
      - torganizer
    ports:
      - 8080:8080
    container_name: webclient

networks:
  torganizer:
    driver: bridge