FROM jenkins

COPY jenkins-init.groovy /usr/share/jenkins/ref/init.groovy.d/jenkins-init.groovy
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt