== Tips for using Docker

IP der virtuellen Maschine http://192.168.99.100

Allgemein:
stoppen und löschen aller Container
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi -f $(docker images -q)
docker exec -it [name] bash

docker network create torganizer
docker network connect torganizer [name]
docker network inspect torganizer

mysql-8
docker build -t "torganizer/mysql" .
docker run -d -p 3306:3306 --name mysql torganizer/mysql:latest --default-authentication-plugin=mysql_native_password

nexus
docker pull sonatype/nexus3
docker run -d -p 8081:8081 --name nexus3 sonatype/nexus3

sonarqube
docker pull sonarqube
docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube

nginx
docker build -t "torganizer/nginx" .
docker run -d --name nginx -p 80:80 torganizer/nginx:latest

jenkins
docker build -t "torganizer/jenkins" .
docker run -d -p 8282:8080 -p 50000:50000 --name jenkins torganizer/jenkins:latest

etc/hosts
c:\Windows\System32\drivers\etc\hosts
192.168.99.100      qs.docker
192.168.99.100      ci.docker
192.168.99.100      m2repo.docker
192.168.99.100      db.docker