== Tips for using Docker

IP der virtuellen Maschine http://192.168.99.100

Allgemein:
stoppen und löschen aller Container
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi -f $(docker images -q)
docker exec -it [name] bash

docker network create torganizer
docker network connect torganizer [name]
docker network inspect torganizer

docker build -t "torganizer/postgresql" .
docker run -d -p 5432:5432 --name postgresql --network=torganizer "torganizer/postgresql":latest

docker build -t "torganizer/rest" .
docker run -d -p 9080:9080 -e dataSource_serverName=postgresql -e dataSource_user=postgres -e dataSource_password=postgres -e dataSource_portNumber=5432 --name rest --network torganizer "torganizer/rest":latest

docker build -t "torganizer/webclient" .
docker run -d -p 8080:8080 -e "resources_url=http://localhost:9080/rest/resources/" --name webclient --network torganizer "torganizer/webclient":latest


docker build -t "torganizer/mysql" .
docker run -d --name mysql --network=torganizer "torganizer/postgresql":latest
docker run -d -p 9080:9080 -e dataSource_serverName=mysql -e dataSource_user=root -e dataSource_password=root -e dataSource_portNumber=3306 --name rest --network torganizer "torganizer/rest":latest

nexus
docker pull sonatype/nexus3
docker run -d -p 8081:8081 --name nexus3 sonatype/nexus3

sonarqube
docker pull sonarqube
docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube

nginx
docker build -t "torganizer/nginx" .
docker run -d --name nginx -p 80:80 torganizer/nginx:latest

jenkins
docker build -t "torganizer/jenkins" .
docker run -d -p 8282:8080 -p 50000:50000 --name jenkins torganizer/jenkins:latest

etc/hosts
c:\Windows\System32\drivers\etc\hosts
192.168.99.100      qs.docker
192.168.99.100      ci.docker
192.168.99.100      m2repo.docker
192.168.99.100      db.docker